### ISSUE TITLE
install_path created with 777 permissions in SSHDeployer

### ISSUE THREAD

**Issue by criccomini** [linkedin/Zopkio#43]
It seems that the SSHDeployer will create the install_path directory with 777 permissions:

    $ ls -l /tmp/samza-tests/deploy/
    total 16
    drwxrwxrwx 4 criccomi criccomi 4096 Jan  5 22:43 kafka
    drwxrwxrwx 3 criccomi criccomi 4096 Jan  5 22:43 yarn_nm
    drwxrwxrwx 3 criccomi criccomi 4096 Jan  5 22:42 yarn_rm
    drwxrwxrwx 4 criccomi criccomi 4096 Jan  5 22:42 zookeeper

It seems like it'd be a bit safer to have it be 755, or something.

**Comment by jdehrlich** [comment]
fixed in version 0.1.11
