### ISSUE TITLE
Programmatically set environment variables

### ISSUE THREAD

**Issue by criccomini** [linkedin/Zopkio#45]
When deploying things and running tests, it'd be nice if we could specify environment variables to be used on all remote machines. For example, we might wish to set JAVA_HOME to some specific path (e.g. if we want to run integration tests against Java 7). We might want to set YARN_HOME to some deployment directory, as well. Zopkio doesn't seem to provide a mechanism for me to do this.

**Comment by arpras** [comment]
This feature is added. It can be passed to the ssh deployer by setting the env config.

For the zookeeper example , we can set the environment variable JAVA_HOME as follows.

    env_dict = {'JAVA_HOME':'/export/apps/jdk/current'}

  zookeper_deployer = adhoc_deployer.SSHDeployer("zookeeper",
      {'pid_keyword': "zookeeper",
       'executable': runtime.get_active_config('zookeeper_exec_location'),
       'env':env_dict,
       'extract': True,
       'post_install_cmds':runtime.get_active_config('zookeeper_post_install_cmds'),
       'stop_command':runtime.get_active_config('zookeeper_stop_command'),
       'start_command': runtime.get_active_config('zookeeper_start_command')})
  runtime.set_deployer("zookeeper", zookeper_deployer)
