### ISSUE TITLE
Support for running tests continuously

### ISSUE THREAD

**Issue by navina** [linkedin/Zopkio#59]
We more often want to run the same test or set of tests over and over again. The scenario looks something like:
```
LOOP (upto N times) {
  Run Test
  Validate Test
  [Optional] Reset System State
  Goto LOOP 
}
```

We can also extend this continuous behavior across multiple tests, although I think this will bring up the question of ***maintaining ordering*** across the tests.
```
LOOP (upto N times) {
  Run test1
  Validate test1
  [Optional] Reset System State
  Run test2
  Validate test2
  ...
  Goto LOOP
}
```
By adding continuous testing support, we can, in future, extend support to run the Zopkio tests via Hudson or other CI tool.

**Comment by arpras** [comment]
These features should be supported in the latest version of zopkio (0.1.14). I have also added a section at the end of the README on how to run few examples that allow running multiple iterations for each test and how to enforce order across multiple tests in case we are looping over entire test suite.
