### ISSUE TITLE
Support failure injection 

### ISSUE THREAD

**Issue by navina** [linkedin/Zopkio#60]
A lot of distributed systems want to test for resilience/recovery. This means Zopkio should have the ability to bring down/kill system components and wait for recovery before validating the state of the system. Scenario would look something like:

```
Setup environment & start all processes
components <- list of components to fail
LOOP (upto n times) {
  Kill a random, say component[i]
  [Optional] Restart component[i]            // -> This can be for cases where the component does not auto-recover, unless it is specifically restarted. For example, Samza depends on Kafka brokers. If we kill a broker, they don't recover automatically. It has to be restarted. 
  Wait for recovery
  Verify system state [ can also validate recovery time, etc ]
  [Optional] Reset system
  Goto LOOP
}
```
User must be able to specify how to fail each component. A component can be failed by:
* using kill cmd with a pid
* using an application specific kill operation / function definition

**Comment by arpras** [comment]
Support for this feature was added in the form a test recipe.  See example test section
Example test file : test_resilience.py.
example test command : zopkio examples/server_client/client_resilience.py
