### ISSUE TITLE
Providing sufficient process isolation for running tests in a shared environment

### ISSUE THREAD

**Issue by navina** [linkedin/Zopkio#61]
If a user-defined deployer does terminate the test suite properly, it might leave behind some orphaned processes.. This can cause issues when the same or new test is deployed on the same host. Imagine a world where the test machines are shared. 
It will be good if the framework provides a way to check for orphaned processes and clear the machine before setting up the test environment. 
I can think about this in 2 ways:
* Maintain a global state with all the pids that were generated by the test suite and manually, kill them after you teardown the suite. 
* Run each test suite in its own VM , although I am not sure how difficult it is to enforce this kind of isolation.

**Comment by arpras** [comment]
>>Maintain a global state with all the pids that were generated by the test suite and manually, kill them after you teardown the suite.

This should be implemented in the latest version.
