### ISSUE TITLE
Code coverage report

### ISSUE THREAD

**Issue by chuongddh** [linkedin/Zopkio#74]
Hi,

I just wonder if Zopkio support any form of code coverage report? If not, is there feasible plan to support this feature?

Thanks and Regards,
Chuong

**Comment by arpras** [comment]
Hi Chuong,

I am glad you are interested in Zopkio.
We designed Zopkio for more of black box integration testing. Code Coverage is something that can be instrumented in the way you start your test. What we can eventually add in zopkio is way to pull these results and display them.

For example, you can use something like emma : http://emma.sourceforge.net/intro.html
In the provided server_client example, you can install emma.jar along the others and change the start command to instrument coverage.
eg: java -cp emma.jar emmarun -jar AdditionClient.jar

We have a zopkio google groups for discussions : zopkio@googlegroups.com.

Also I would really appreciate if you can tell me know what you are using Zopkio for ?

Thanks
