### ISSUE TITLE
Zopkio Test Result Format

### ISSUE THREAD

**Issue by chuongddh** [linkedin/Zopkio#80]
Hello,

I would like to ask if Zokio support any other type of status reporting like XML, Junit format... This would be great help for us to plug the framework in continuous integration infrastructure like Jenkins.

Thanks and Regards,
Chuong

**Comment by arpras** [comment]
Hi Chuong,

Current it does not. However I would be really happy to accept a pull request from you if you want to add that change and contribute to this open source project.
Also if you don't mind can you tell me what you are using Zopkio for ? This information helps us understand more about our customers and might give insights about possible new usage that we have not thought about.

Thanks very much.
-Arun

**Comment by chuongddh** [comment]
Hi Arun,

Thank you for your response. We are using Zopkio to build integration test structure for our project. Then we would like to set up Zopkio with our test in Jenkins for daily test and reporting. And Jenkins can interpret test result with Xunit format (like Junit). So it would be great if Zopkio can produce test result in Junit xml format with details of failed test case.

Thanks and Regards,
Chuong

**Comment by arpras** [comment]
Thanks very much Chuong. If you don't mind can you tell me which organization you belong to as well.

We currently don't have this particular feature in our immediate roadmap. However we will be very happy to review and accept any pull request.

Thanks.

**Comment by chuongddh** [comment]
Hi Arpras,

Thank you for your response. I'm with PubNub.

Kind Regards,
Chuong
